listen_interface: 0.0.0.0
listen_port: 9090

targets:
  - http://localhost:8080

rate_limit_avg_second: 300
rate_limit_burst_second: 500

idp_metadata_url: https://some.idp/metadata/32093329
allow_idp_initiated: False
service_root_url: http://localhost:9090

cert_path: myservice.cert
key_path: myservice.key

cookie_max_age: 4h

# incoming `memberOf` attribute would be added as a `X-Saml-Memberof` header
add_attributes_as_headers:
  - memberOf
  - Username

# panic, fatal, error, warn, info, debug
# debug logs cookie information!
log_level: info
